export ZSH=$HOME/.dotfiles/plugins/oh-my-zsh
export ZSH_THEME="eastwood"

export EDITOR='vim'

export LANG=ja_JP.UTF-8
export LESSCHARSET=UTF-8

export TERM="xterm-256color"

setopt no_flow_control

export PATH=/usr/local/share/npm/bin:/usr/local/bin:$HOME/.rbenv/shims:$HOME/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/lib

# setting rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

for f (~/.zsh/sources/peco/*) source "${f}"

eval "$(direnv hook zsh)"

export PATH=$PATH:~/.phpenv/bin
eval "$(phpenv init -)"

# enable oh-my-zsh
plugins=(brew bundler git git-extras rbenv vagrant github docker)
source $ZSH/oh-my-zsh.sh

# for golang
export GOPATH=$HOME
export PATH=$PATH:$GOPATH/bin

# for zsh-notify
export SYS_NOTIFIER="/usr/local/bin/terminal-notifier"
export NOTIFY_COMMAND_COMPLETE_TIMEOUT=10

if [ -n "$TMUX" ]; then
    alias pbcopy="reattach-to-user-namespace pbcopy"
fi

export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/yucchiy/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem

# key-bindings
bindkey '^h' peco-select-history
bindkey '^s' peco-src

# alias
alias bi="bundle install"
alias be="bundle exec"
alias pk="peco-pkill"
alias -g B='`git branch | peco | sed -e "s/^\*[ ]*//g"`'
alias -g BA='`git branch -a | peco | sed -e "s/^\*[ ]*//g"`'
alias tiga="tig --all"
