export ZSH=$HOME/.dotfiles/plugins/oh-my-zsh
export ZSH_THEME="wezm"

export EDITOR='vim'

export LANG=ja_JP.UTF-8

export LESSCHARSET=UTF-8

export TERM="xterm-256color"

setopt no_flow_control

export PATH=/usr/local/share/npm/bin:/usr/local/bin:$HOME/.rbenv/shims:$HOME/bin:$PATH:$HOME/.composer/vendor/bin:$HOME/.cargo/bin
export LD_LIBRARY_PATH=/usr/local/lib


# setting rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

for f (~/.zsh/sources/peco/*) source "${f}"

eval "$(direnv hook zsh)"

# enable oh-my-zsh
plugins=(brew bundler git git-extras rbenv vagrant github docker)
source $ZSH/oh-my-zsh.sh

export PS1='$(git_prompt_info)%(?,,%{${fg_bold[white]}%}[%?]%{$reset_color%} )%(?,%{$fg[green]%},%{$fg[red]%})%#%{$reset_color%} '
export RPS1=''

export ZSH_THEME_GIT_PROMPT_DIRTY="%{%})%{%}✘%{%}"


# for golang
export GOPATH=$HOME
export PATH=$PATH:$GOPATH/bin

# for zsh-notify
export SYS_NOTIFIER="/usr/local/bin/terminal-notifier"
export NOTIFY_COMMAND_COMPLETE_TIMEOUT=10

if [ -n "$TMUX" ]; then
    alias pbcopy="reattach-to-user-namespace pbcopy"
fi

eval "$(docker-machine env default)"

export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem

# key-bindings
bindkey '^h' peco-select-history
bindkey '^s' peco-src

# alias
alias bi="bundle install"
alias be="bundle exec"
alias pk="peco-pkill"
alias -g B='`git branch | peco | sed -e "s/^\*[ ]*//g"`'
alias -g BA='`git branch -a | peco | sed -e "s/^\*[ ]*//g"`'
alias tiga="tig --all"
alias vim="nvim"

# The next line updates PATH for the Google Cloud SDK.
source '/Users/yucchiy/Downloads/google-cloud-sdk/path.zsh.inc'

# The next line enables shell command completion for gcloud.
source '/Users/yucchiy/Downloads/google-cloud-sdk/completion.zsh.inc'

# Add environment variable COCOS_CONSOLE_ROOT for cocos2d-x
export COCOS_CONSOLE_ROOT=/usr/share/cocos2d-x/3.8/tools/cocos2d-console/bin
export PATH=$COCOS_CONSOLE_ROOT:$PATH

# Add environment variable COCOS_TEMPLATES_ROOT for cocos2d-x
export COCOS_TEMPLATES_ROOT=/usr/share/cocos2d-x/3.8/templates
export PATH=$COCOS_TEMPLATES_ROOT:$PATH

# Add environment variable NDK_ROOT for cocos2d-x
export NDK_ROOT=/usr/share/android-ndk/r10e
export PATH=$NDK_ROOT:$PATH

# Add environment variable ANDROID_SDK_ROOT for cocos2d-x
export ANDROID_SDK_ROOT=/usr/local/Cellar/android-sdk/24.3.4
export PATH=$ANDROID_SDK_ROOT:$PATH
export PATH=$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:$PATH

# Add environment variable ANT_ROOT for cocos2d-x
export ANT_ROOT=/usr/local/Cellar/ant/1.9.6/bin
export PATH=$ANT_ROOT:$PATH
